// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAe9YLGVqkFukQkfTEp0MSOgkt3bJojzAI',
    appId: '1:781111802782:web:54da5bf72c364ba5e1b48f',
    messagingSenderId: '781111802782',
    projectId: 'crmapp-dd7e7',
    authDomain: 'crmapp-dd7e7.firebaseapp.com',
    storageBucket: 'crmapp-dd7e7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAM-tirRwU1tkqdRxMZASMFWvv5Y8OMDqM',
    appId: '1:781111802782:android:3534950c55ef21ebe1b48f',
    messagingSenderId: '781111802782',
    projectId: 'crmapp-dd7e7',
    storageBucket: 'crmapp-dd7e7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDujrmzrBpsSKmUIY4xtS_reGWEBUCoYuE',
    appId: '1:781111802782:ios:5bf167c1079e4cd6e1b48f',
    messagingSenderId: '781111802782',
    projectId: 'crmapp-dd7e7',
    storageBucket: 'crmapp-dd7e7.firebasestorage.app',
    iosBundleId: 'com.example.salesbets',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDujrmzrBpsSKmUIY4xtS_reGWEBUCoYuE',
    appId: '1:781111802782:ios:5bf167c1079e4cd6e1b48f',
    messagingSenderId: '781111802782',
    projectId: 'crmapp-dd7e7',
    storageBucket: 'crmapp-dd7e7.firebasestorage.app',
    iosBundleId: 'com.example.salesbets',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAe9YLGVqkFukQkfTEp0MSOgkt3bJojzAI',
    appId: '1:781111802782:web:b1667ce8c14de2c8e1b48f',
    messagingSenderId: '781111802782',
    projectId: 'crmapp-dd7e7',
    authDomain: 'crmapp-dd7e7.firebaseapp.com',
    storageBucket: 'crmapp-dd7e7.firebasestorage.app',
  );
}
